// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwsmszwrlmfnkkfavycb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3c21zendybG1mbmtrZmF2eWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NDY3MTUsImV4cCI6MjA2NjIyMjcxNX0.ogdGNsaD3PdQzZWukL_X63pIPpPcXsC-rsS8LBQAHyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);